version: '3.8'

services:
        postgres:
                image: postgres:latest
                container_name: postgres_container
                environment:
                        POSTGRES_USER: dst_projet
                        POSTGRES_PASSWORD: dst_projet
                        POSTGRES_DB: postgres
                volumes:
                        - ~/projet/app/pg_data:/var/lib/postgresql/data
                        - ~/projet/app/raw_data:/app/raw_data
                        - ~/projet/source/Test_Satisfaction_client/initdb:/docker-entrypoint-initdb.d
                ports:
                        - "5432:5432"
                networks:
                        - project_network

        python_load_pg:
                image: python_load_pg:latest
                container_name: python_load_pg
                depends_on:
                        - postgres
                networks:
                        - project_network

networks:
        project_network:
                external: true

